Repository AlphaWallet/alpha-wallet-ios, pull requests merged in 2022-03, with the labels that each got.

#4037 Add cmd+f keyboard shortcut in Wallet tab to trigger search
  AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
Labels: DX

#4048 Modify func signature to fix typos
  AlphaWallet/Tokens/Coordinators/SingleChainTokenCoordinator.swift
  AlphaWallet/Tokens/Coordinators/TokensCoordinator.swift
Labels: Skip review

#4049 Replace the "..." used when truncating addresses in the middle with the real thing: "…"
  modules/AlphaWalletAddress/AlphaWalletAddress/AlphaWallet.swift
Labels: Skip review

#4103 Blockscan Chat Stathat to Mixpanel
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/Analytics/Coordinators/AnalyticsCoordinator.swift
  AlphaWallet/Analytics/Coordinators/AnalyticsService.swift
  AlphaWallet/Analytics/Coordinators/MixpanelCoordinator.swift
  AlphaWallet/Analytics/Models/AnalyticsTypes.swift
  AlphaWallet/BlockscanChat/BlockscanChat.swift
  AlphaWallet/BlockscanChat/RemoteCounter.swift
  AlphaWallet/InCoordinator.swift
Labels: Skip review

#4107 Remove Subscribable from TokenBalanceService #4106
  AlphaWallet/Accounts/Coordinators/AccountsCoordinator.swift
  AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
  AlphaWallet/Accounts/ViewModels/AccountViewModel.swift
  AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
  AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
  AlphaWallet/Accounts/Views/AccountViewCell.swift
  AlphaWallet/Accounts/Views/WalletSummaryTableViewCell.swift
  AlphaWallet/Accounts/Views/WalletSummaryView.swift
  AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
  AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceFetcher.swift
  AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceService.swift
  AlphaWallet/Core/TokenBalanceService.swift
  AlphaWallet/Core/Types/WalletSummary.swift
  AlphaWallet/Export/Coordinators/PromptBackupCoordinator.swift
  AlphaWallet/InCoordinator.swift
  AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
  AlphaWallet/Sell/ViewControllers/EnterSellTokensCardPriceQuantityViewController.swift
  AlphaWallet/Tokens/ViewControllers/TokenViewController.swift
  AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
  AlphaWallet/Tokens/ViewModels/TokenViewControllerViewModel.swift
  AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift
  AlphaWallet/Transfer/ViewControllers/SendViewController.swift
  AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
  AlphaWalletTests/Factories/WalletSession.swift
  AlphaWalletTests/Settings/Coordinators/SettingsCoordinatorTests.swift
  AlphaWalletTests/Transfer/ViewControllers/SendViewControllerTests.swift
Labels: WIP. Don't Merge
