Repository AlphaWallet/alpha-wallet-ios, pull requests merged in 2022-01, with the labels that each got.

#3579 24 word seed phrase feature
  AlphaWallet/Core/Features.swift
  AlphaWallet/KeyManagement/EtherKeystore.swift
  AlphaWallet/Localization/en.lproj/Localizable.strings
  AlphaWallet/Localization/es.lproj/Localizable.strings
  AlphaWallet/Localization/ja.lproj/Localizable.strings
  AlphaWallet/Localization/ko.lproj/Localizable.strings
  AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
  AlphaWallet/UI/Form/HDWallet+Extension.swift
  AlphaWallet/UI/Form/MnemonicLengthRule.swift
  AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
Labels: WIP. Don't Merge

#3598 Update WebImageView with right width scale #3597
  AlphaWallet/Tokens/Collectibles/Views/TokensCardCollectionInfoPageView.swift
  AlphaWallet/Tokens/Views/OpenSea/OpenSeaNonFungibleTokenViewCell.swift
  AlphaWallet/Tokens/Views/OpenSea/WebImageView.swift
  AlphaWallet/UI/TokenImageView.swift
  AlphaWallet/WebImage/image-scale.min.js
  AlphaWallet/WebImage/images/tokenPlaceholderLarge.pdf
  AlphaWallet/WebImage/jquery-3.6.0.min.js
  AlphaWallet/WebImage/jquery.cacheImages.min.js
  AlphaWallet/WebImage/page.js
  AlphaWallet/WebImage/web_image.html
Labels: WIP. Don't Merge

#3595 Allow user to select one or more CustomRPC from a list
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcModel.swift
  AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcPresentationController.swift
  AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcView.swift
  AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcViewController.swift
  AlphaWallet/AddMultipleCustomRpc/AddMultipleCustomRpcViewModel.swift
  AlphaWallet/Assets.xcassets/iconsIllustrationsSearchResults.imageset/Contents.json
  AlphaWallet/Assets.xcassets/iconsIllustrationsSearchResults.imageset/iconsIllustrationsSearchResults@2x.png
  AlphaWallet/Assets.xcassets/iconsIllustrationsSearchResults.imageset/iconsIllustrationsSearchResults@3x.png
  AlphaWallet/Assets.xcassets/mine.colorset/Contents.json
  AlphaWallet/Core/Helpers/ExecuteOnceOnly.swift
  AlphaWallet/Localization/en.lproj/Localizable.strings
  AlphaWallet/Localization/es.lproj/Localizable.strings
  AlphaWallet/Localization/ja.lproj/Localizable.strings
  AlphaWallet/Localization/ko.lproj/Localizable.strings
  AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
  AlphaWallet/Rpc Network/AvailableRpcNetwork.swift
  AlphaWallet/Rpc Network/chains.zip
  AlphaWallet/Settings/Coordinators/SaveCustomRpcCoordinator.swift
  AlphaWallet/Settings/Models/SaveCustomRpcOverallModel.swift
  AlphaWallet/Settings/Types/CustomRpcTableViewSection.swift
  AlphaWallet/Settings/Types/SaveCustomRpcBrowseDataController.swift
  AlphaWallet/Settings/Types/TableViewSection.swift
  AlphaWallet/Settings/ViewControllers/SaveCustomRpcBrowseViewController.swift
  AlphaWallet/Settings/ViewControllers/SaveCustomRpcManualEntryViewController.swift
  AlphaWallet/Settings/ViewControllers/SaveCustomRpcOverallViewController.swift
  AlphaWallet/Settings/ViewModels/SaveCustomRpcManualEntryViewModel.swift
  AlphaWallet/Settings/Views/EmptyTableView.swift
  AlphaWallet/Settings/Views/SaveCustomRpcBrowseView.swift
  AlphaWallet/Settings/Views/SaveCustomRpcManualEntryView.swift
  AlphaWallet/Settings/Views/SaveCustomRpcOverallView.swift
  AlphaWallet/Style/AppStyle.swift
  AlphaWalletTests/Rpc Network/RpcNetworkTestCase.swift
Labels: For user testing

#3707 Fix vulnerabilities by GitHub for parse-link-header CVE-2021-23490
  package.json
  yarn.lock
Labels: Skip review

#3717 Update CODEOWNERS file to specify delicate parts of system
  .github/CODEOWNERS
Labels: Skip review

#3547 Fixed code on Wallet main screen that crashed when token row was swiped to delete
  AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
  AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
Labels: Bug

#3737 Make Travis only run on iOS 15, dropping 14.5 temporarily for speed
  .travis.yml
Labels: Skip review

#3727 Refactor custom URL scheme handling (eg. ethereum:) and universal link handling (eg. https://aw.app) #3719
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/AppCoordinator.swift
  AlphaWallet/AppDelegate.swift
  AlphaWallet/Browser/Coordinators/DappBrowserCoordinator.swift
  AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
  AlphaWallet/Core/Coordinators/CustomUrlSchemeCoordinator.swift
  AlphaWallet/Core/Coordinators/PaymentFlowFromEip681UrlResolver.swift
  AlphaWallet/Core/Types/DeepLink.swift
  AlphaWallet/InCoordinator.swift
  AlphaWallet/Market/Coordinators/ImportMagicLinkCoordinator.swift
  AlphaWallet/Market/Coordinators/UniversalLinkInPasteboardCoordinator.swift
  AlphaWallet/Share/UrlSchemeCoordinator.swift
  AlphaWallet/TokenScriptClient/Coordinators/AssetDefinitionStoreCoordinator.swift
  AlphaWallet/WalletConnect/Types/WalletConnect.swift
  AlphaWalletTests/Coordinators/InCoordinatorTests.swift
  AlphaWalletTests/Market/ImportMagicLinkCoordinatorTests.swift
Labels: WIP. Don't Merge

#3754 Remove spurious colon in copy
  AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
Labels: Skip review

#3740 Removed unused Formatters, CurrencyFormatter and other NumberFormatters replaced with Formatters #3531
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/Accounts/ViewModels/WalletSummaryViewModel.swift
  AlphaWallet/Alerts/ViewControllers/EditPriceAlertViewController.swift
  AlphaWallet/Alerts/ViewModels/EditPriceAlertViewModel.swift
  AlphaWallet/Browser/Coordinators/QRCodeResolutionCoordinator.swift
  AlphaWallet/Core/Coordinators/Alerts/Types/PriceAlert.swift
  AlphaWallet/Core/Formatters/CurrencyFormatter.swift
  AlphaWallet/Core/Types/ERC20BalanceViewModel.swift
  AlphaWallet/Core/Types/NativecryptoBalanceViewModel.swift
  AlphaWallet/Core/Types/WalletBalance.swift
  AlphaWallet/Core/Types/WalletSummary.swift
  AlphaWallet/Export/ViewModels/PromptBackupWalletAfterExceedingThresholdViewViewModel.swift
  AlphaWallet/Foundation/DecimalFormatter.swift
  AlphaWallet/Foundation/Formatter.swift
  AlphaWallet/Foundation/StringFormatter.swift
  AlphaWallet/Tokens/ViewModels/EthTokenViewCellViewModel.swift
  AlphaWallet/Tokens/ViewModels/FungibleTokenViewCellViewModel.swift
  AlphaWallet/Transactions/ViewModels/BalanceViewModel.swift
  AlphaWallet/Transactions/Views/TokenHistoryChartView.swift
  AlphaWallet/Transactions/Views/XYMarkerView.swift
  AlphaWallet/Transfer/Types/CurrencyRate+Fee.swift
  AlphaWallet/Transfer/ViewControllers/SendViewController.swift
  AlphaWallet/Transfer/ViewModels/ConfigureTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/SendHeaderViewViewModel.swift
  AlphaWalletTests/Foundation/DecimalNumberFormatterTest.swift
  AlphaWalletTests/Foundation/FormatterTests.swift
Labels: WIP. Don't Merge

#3792 Tweak message displayed when gas fee to be used for a transaction is considered to be too high
  AlphaWallet/Localization/en.lproj/Localizable.strings
  AlphaWallet/Localization/es.lproj/Localizable.strings
Labels: Skip review

#3746 Display traits for NFTs (ERC721 and ERC1155) retrieved from OpenSea #3741
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/Core/Views/SegmentedControl.swift
  AlphaWallet/Core/Views/SelfResizableCollectionView.swift
  AlphaWallet/Core/Views/TextField.swift
  AlphaWallet/Core/Views/WebImageView.swift
  AlphaWallet/Localization/en.lproj/Localizable.strings
  AlphaWallet/Localization/es.lproj/Localizable.strings
  AlphaWallet/Localization/ja.lproj/Localizable.strings
  AlphaWallet/Localization/ko.lproj/Localizable.strings
  AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
  AlphaWallet/TokenScriptClient/Models/AssetAttributeSyntaxValue.swift
  AlphaWallet/Tokens/Collectibles/ViewControllers/Erc1155TokenInstanceViewController.swift
  AlphaWallet/Tokens/Collectibles/ViewModels/Erc1155TokenInstanceViewModel.swift
  AlphaWallet/Tokens/Helpers/TokenInstanceViewConfigurationHelper.swift
  AlphaWallet/Tokens/ViewControllers/PeekOpenSeaNonFungibleTokenViewController.swift
  AlphaWallet/Tokens/ViewModels/OpenSeaNonFungibleTokenCardRowViewModel.swift
  AlphaWallet/Tokens/ViewModels/TokenInstanceInfoPageViewModel.swift
  AlphaWallet/Tokens/ViewModels/TokenListFormatRowViewModel.swift
  AlphaWallet/Tokens/ViewModels/TokenViewControllerTransactionCellViewModel.swift
  AlphaWallet/Tokens/ViewModels/TokensCardViewModel.swift
  AlphaWallet/Tokens/Views/BaseTokenListFormatTableViewCell.swift
  AlphaWallet/Tokens/Views/OpenSea/OpenSeaAttributeCollectionView.swift
  AlphaWallet/Tokens/Views/TokenCardTableViewCellWithCheckbox.swift
  AlphaWallet/Tokens/Views/TokenCardsViewControllerHeader.swift
  AlphaWallet/Tokens/Views/TokenInstanceInfoPageView.swift
  AlphaWallet/Tokens/Views/TokenListFormatRowView.swift
  AlphaWallet/Tokens/Views/TokenListFormatTableViewCellWithCheckbox.swift
  AlphaWallet/Tokens/Views/TokenListFormatTableViewCellWithoutCheckbox.swift
  AlphaWallet/Tokens/Views/TokenViewControllerTransactionCell.swift
  AlphaWallet/Tokens/Views/UITableViewCell+TokenCell.swift
Labels: WIP. Don't Merge

#3814 Update README to be explicit about not opening the xcodeproj file
  README.md
Labels: Skip review

#3818 Include the URL in log for errors encountered when accessing URLs
  AlphaWallet/Extensions/Session+PromiseKit.swift
Labels: Skip review

#3844 Fix: remove duplicate file reference in Xcode project
  AlphaWallet.xcodeproj/project.pbxproj
Labels: Skip review

#3845 Modifed code so that an error message is displayed if MFMailComposeViewController.canSendMail() returns false
  AlphaWallet/Localization/en.lproj/Localizable.strings
  AlphaWallet/Localization/es.lproj/Localizable.strings
  AlphaWallet/Localization/ja.lproj/Localizable.strings
  AlphaWallet/Localization/ko.lproj/Localizable.strings
  AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings
  AlphaWallet/Settings/Types/ServiceProvider.swift
Labels: WIP. Don't Merge
