Repository AlphaWallet/alpha-wallet-ios, pull requests merged in 2022-11, with the labels that each got.

#5712 [Refactoring] types renaming, updating view models inputs
  AlphaWallet/Common/ViewControllers/AcceptProposalViewController.swift
  AlphaWallet/Common/ViewModels/AcceptDeepLinkViewModel.swift
  AlphaWallet/Common/ViewModels/AcceptProposalViewModel.swift
  AlphaWallet/Common/ViewModels/AcceptWalletConnectSessionViewModel.swift
  AlphaWallet/Swap/SwapOptions/ViewControllers/SwapOptionsViewController.swift
  AlphaWallet/Swap/SwapOptions/ViewModels/SwapOptionsViewModel.swift
  AlphaWallet/Swap/SwapRoutes/ViewControllers/SelectSwapRouteViewController.swift
  AlphaWallet/Swap/SwapRoutes/ViewModels/SelectSwapRouteViewModel.swift
  AlphaWallet/Swap/SwapTools/ViewControllers/SelectSwapToolViewController.swift
  AlphaWallet/Swap/SwapTools/ViewModels/SelectSwapToolViewModel.swift
  AlphaWallet/Swap/SwapTools/ViewModels/SelectedSwapToolsCollectionViewModel.swift
  AlphaWallet/Swap/SwapTools/Views/SelectedSwapToolsCollectionView.swift
  AlphaWallet/Tokens/ViewModels/TokensViewModel.swift
  AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/CancelTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/ClaimPaidErc875MagicLinkViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/DappOrWalletConnectTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SectionProtocol.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SendFungiblesTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SendNftTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SpeedupTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SwapTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmation/TokenScriptTransactionViewModel.swift
  AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
Labels: Skip review

#5713 [Refactor] refactor request screen
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/Common/Helpers/ScreenChecker.swift
  AlphaWallet/Common/Views/RoundedEnsView.swift
  AlphaWallet/Common/Views/ViewModels/RoundedEnsViewModel.swift
  AlphaWallet/Common/Views/ViewRounding.swift
  AlphaWallet/Extensions/Control+Publishers.swift
  AlphaWallet/Transfer/Coordinators/RequestCoordinator.swift
  AlphaWallet/Transfer/ViewControllers/RequestViewController.swift
  AlphaWallet/Transfer/ViewModels/RequestViewModel.swift
Labels: Skip review

#5714 [Refactoring] update edit bookmark screen
  AlphaWallet/Browser/ViewControllers/EditBookmarkViewController.swift
  AlphaWallet/Browser/ViewModel/EditBookmarkViewModel.swift
Labels: Skip review

#5715 [Refactoring] update rename wallet name screen
  AlphaWallet/Browser/ViewControllers/EditBookmarkViewController.swift
  AlphaWallet/Common/Types/AppStyle.swift
  AlphaWallet/Common/Views/AddressTextField.swift
  AlphaWallet/Common/Views/TextField.swift
  AlphaWallet/Common/Views/TextView.swift
  AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
  AlphaWallet/Wallet/ViewControllers/RenameWalletViewController.swift
  AlphaWallet/Wallet/ViewModels/RenameWalletViewModel.swift
Labels: Skip review

#5719 Fix test suite #5716
  AlphaWalletTests/Transfer/ViewModels/RequestViewModelTests.swift
Labels: Skip review

#5720 Added dark mode to Transaction In Progress screen
  AlphaWallet/Transfer/ViewModels/TransactionInProgressViewModel.swift
Labels: WIP. Don't Merge

#5730 refactor callSmartContractCall params
  modules/AlphaWalletFoundation/AlphaWalletFoundation/EtherClient/Models/WaitTillTransactionCompleted.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractDecimals.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractName.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetContractSymbol.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Logic/GetErc20Balance.swift
Labels: Skip review

#5741 remove public from autodetection
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/AutoDetectTransactedTokensOperation.swift
Labels: Skip review

#5747 Fixed UISearchBar dark mode background color in the iOS Document Browser.
  AlphaWallet/Common/Types/AppStyle.swift
Labels: UI

#5753 Fixed dark mode of background of Round button display wallet address
  AlphaWallet/Common/Types/Configuration.swift
  AlphaWallet/Common/Views/ViewModels/RoundedEnsViewModel.swift
Labels: UI

#5761 [Refactor] Rename property to be more intention revealing.
  AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
  AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
Labels: Skip review

#5764 Remove unnecessary import
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/Validators/MnemonicInWordListValidator.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/Validators/MnemonicLengthValidator.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Market/OrderHandler.swift
Labels: Skip review

#5779 Enable swap
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Features/Features.swift
Labels: Skip review

#5783 Refactoring fungible token view controller
  AlphaWallet/Tokens/ViewControllers/FungibleTokenViewController.swift
Labels: Skip review

#5791 Refactor settings screen
  AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
  AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
  AlphaWallet/Settings/ViewModels/SettingTableViewCellViewModel.swift
  AlphaWallet/Settings/ViewModels/SettingViewHeaderViewModel.swift
  AlphaWallet/Settings/ViewModels/SettingsViewModel.swift
Labels: Skip review

#5792 Refactor advanced settings screen
  AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
  AlphaWallet/Settings/ViewModels/AdvancedSettingsViewModel.swift
Labels: Skip review

#5798 fix switching chains in walletconnect doesnt appear to work, tapping a chain does nothing 5797
  AlphaWallet/WalletConnect/Coordinator/WalletConnectSessionCoordinator.swift
Labels: Skip review

#5650 move exporting keystore json to background queue #5646
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/AppCoordinator.swift
  AlphaWallet/Backup/Coordinators/BackupCoordinator.swift
  AlphaWallet/Common/Types/AppStyle.swift
  AlphaWallet/Common/Views/TextField.swift
  AlphaWallet/Common/Views/TextView.swift
  AlphaWallet/Settings/Coordinators/ExportJsonKeystoreCoordinator.swift
  AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
  AlphaWallet/Settings/ViewControllers/ExportJsonKeystoreFileViewController.swift
  AlphaWallet/Settings/ViewControllers/ExportJsonKeystorePasswordViewController.swift
  AlphaWallet/Settings/ViewModels/ExportJsonKeystoreFileViewModel.swift
  AlphaWallet/Settings/ViewModels/ExportJsonKeystorePasswordViewModel.swift
  AlphaWallet/Settings/Views/ExportJsonKeystoreFileView.swift
  AlphaWallet/Settings/Views/ExportJsonKeystorePasswordView.swift
  AlphaWallet/Wallet/ViewControllers/ImportWalletViewController.swift
  AlphaWallet/Wallet/ViewControllers/ShowSeedPhraseViewController.swift
  AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
  AlphaWalletTests/Coordinators/AppCoordinatorTests.swift
  AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
  AlphaWalletTests/Factories/FakeEtherKeystore.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Helpers/StringValidator.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/EtherKeystore.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/Keystore.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/KeyManagement/LegacyFileBasedKeystore.swift
Labels: WIP. Don't Merge

#5809 tweak wallet connect screens
  AlphaWallet.xcodeproj/project.pbxproj
  AlphaWallet/Common/Types/AppStyle.swift
  AlphaWallet/Common/Views/ButtonsBar/ButtonsBarBackgroundView.swift
  AlphaWallet/Common/Views/LabeledServerImageView.swift
  AlphaWallet/Common/Views/ViewModels/LabeledServerImageViewModel.swift
  AlphaWallet/Extensions/UIView.swift
  AlphaWallet/Swap/Swap/SwapTokensViewController.swift
  AlphaWallet/Swap/Swap/Views/SwapQuoteDetailsView.swift
  AlphaWallet/Swap/Swap/Views/SwapStepsView.swift
  AlphaWallet/Tokens/Views/ActiveWalletSessionView.swift
  AlphaWallet/WalletConnect/View/WalletConnectRowView.swift
  AlphaWallet/WalletConnect/View/WalletConnectSessionCell.swift
  AlphaWallet/WalletConnect/View/WalletConnectSessionFieldView.swift
  AlphaWallet/WalletConnect/ViewController/WalletConnectSessionViewController.swift
  AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
  AlphaWallet/WalletConnect/ViewModel/WallerConnectRowViewModel.swift
  AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionCellViewModel.swift
  AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionDetailsViewModel.swift
  AlphaWallet/WalletPupup/WalletPupupViewController.swift
  AlphaWallet/WalletPupup/WalletPupupViewModel.swift
Labels: Skip review

#5814 chore code formatting
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Config.swift
Labels: Skip review

#5816 [Chore] Fix SwiftLint warnings
  AlphaWallet/Wallet/ViewControllers/VerifySeedPhraseViewController.swift
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/TokensAutodetector/ContractToImportStorage.swift
Labels: Skip review

#5825 Update AlphaWallet logo image used in Ramp
  modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/Constants.swift
Labels: Skip review

#5826 [Tests] Fix broken tests
  AlphaWalletTests/EtherClient/EtherKeystoreTests.swift
Labels: Skip review

#5833 [Refactoring] extract table view definition to extension
  AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
  AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
  AlphaWallet/Settings/ViewControllers/ChooseSendPrivateTransactionsProviderViewController.swift
  AlphaWallet/Settings/ViewControllers/ConsoleViewController.swift
  AlphaWallet/Settings/ViewControllers/ServersViewController.swift
  AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
  AlphaWallet/Settings/ViewControllers/SupportViewController.swift
  AlphaWallet/Settings/ViewControllers/ToolsViewController.swift
  AlphaWallet/Settings/ViewModels/ChooseSendPrivateTransactionsProviderViewModel.swift
Labels: Skip review

#5834 Refactor table views
  AlphaWallet/Accounts/ViewControllers/AccountsViewController.swift
  AlphaWallet/Accounts/ViewModels/AccountsViewModel.swift
  AlphaWallet/Activities/Views/ActivitiesView.swift
  AlphaWallet/Alerts/Views/PriceAlertsPageView.swift
  AlphaWallet/Browser/ViewControllers/BookmarksViewController.swift
  AlphaWallet/Browser/ViewControllers/BrowserHistoryViewController.swift
  AlphaWallet/Browser/ViewModel/BookmarksViewViewModel.swift
  AlphaWallet/Common/ViewModels/GasViewModel.swift
  AlphaWallet/Extensions/UIView.swift
  AlphaWallet/Features/FeaturesTableViewController.swift
  AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift
  AlphaWallet/Settings/ViewControllers/AdvancedSettingsViewController.swift
  AlphaWallet/Settings/ViewControllers/ChooseSendPrivateTransactionsProviderViewController.swift
  AlphaWallet/Settings/ViewControllers/EnabledServersViewController.swift
  AlphaWallet/Settings/ViewControllers/LocalesViewController.swift
  AlphaWallet/Settings/ViewControllers/SaveCustomRpcOverallViewController.swift
  AlphaWallet/Settings/ViewControllers/ServersViewController.swift
  AlphaWallet/Settings/ViewControllers/SettingsViewController.swift
  AlphaWallet/Settings/ViewControllers/SupportViewController.swift
  AlphaWallet/Settings/ViewControllers/ToolsViewController.swift
  AlphaWallet/Swap/SwapOptions/ViewControllers/SwapOptionsViewController.swift
  AlphaWallet/Swap/SwapRoutes/ViewControllers/SelectSwapRouteViewController.swift
  AlphaWallet/Swap/SwapTools/ViewControllers/SelectSwapToolViewController.swift
  AlphaWallet/TokenScript/ViewControllers/AssetDefinitionsOverridesViewController.swift
  AlphaWallet/Tokens/Collectibles/Coordinators/NFTCollectionCoordinator.swift
  AlphaWallet/Tokens/Collectibles/ViewControllers/NFTAssetListViewController.swift
  AlphaWallet/Tokens/Collectibles/ViewControllers/NFTAssetSelectionViewController.swift
  AlphaWallet/Tokens/Coordinators/AddHideTokensCoordinator.swift
  AlphaWallet/Tokens/ViewControllers/AddHideTokensViewController.swift
  AlphaWallet/Tokens/ViewControllers/SelectTokenViewController.swift
  AlphaWallet/Tokens/ViewControllers/TokensViewController.swift
  AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift
  AlphaWallet/Tokens/ViewModels/SelectTokenViewModel.swift
  AlphaWallet/Transactions/ViewControllers/TransactionsViewController.swift
  AlphaWallet/Transfer/ViewControllers/ConfigureTransactionViewController.swift
  AlphaWallet/Wallet/Views/InitialNetworkSelectionView.swift
  AlphaWallet/WalletConnect/Coordinator/WalletConnectCoordinator.swift
  AlphaWallet/WalletConnect/ViewController/WalletConnectSessionsViewController.swift
  AlphaWallet/WalletConnect/ViewModel/WalletConnectSessionsViewModel.swift
Labels: Skip review

#5869 add missing key 'transaction.id' #5865
  AlphaWallet/Localization/fi.lproj/Localizable.strings
Labels: Skip review
